apiVersion: v1
kind: Pod
metadata:
  name: docktest
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: jenkins/jnlp-slave
      imagePullPolicy: Always
      command: ["tail", "-f", "/dev/null"]
      ports:
        - containerPort: 40000
